// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxulrlyzieqvxrsgfxoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4dWxybHl6aWVxdnhyc2dmeG9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2ODUxMjUsImV4cCI6MjA3MTI2MTEyNX0.pGakaRoFTQJIzwD671BgQPS2xTL3qr2tYHbfljAUztc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});